apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert --volumes=hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: snmp-exporter
  name: snmp-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snmp-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert --volumes=hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/stat-default: "true"
        io.kompose.service: snmp-exporter
    spec:
      containers:
        - image: prom/snmp-exporter:v0.22.0
          name: snmp-exporter
          ports:
            - containerPort: 9116
              hostPort: 9116
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/snmp_exporter/snmp.yml
              name: snmp-exporter-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/prometheus/snmp.yml
          name: snmp-exporter-hostpath0
status: {}
