on: 
    push:
      paths-ignore:
        - ".devcontainer/**"
        - ".github/README.md"
        - ".gitignore"
        - "LICENSE"
        - "network/**"
        - "server/**"
  
jobs:
    deploy:
      defaults:
        run:
          working-directory: docs
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
        statuses: write
      name: Deploy to Cloudflare Pages
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - uses: actions/cache@v3
          id: node_modules_cache_id
          env:
            cache-name: cache-node-modules
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
        - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
          run: npm install
        - name: Build
          run: npm run build
        - name: Publish
          uses: cloudflare/pages-action@1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: technotut-infra
            directory: ./docs/build
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            wranglerVersion: '3'